import logging
import math
import re

import knime.extension as knext
from topoq_category import topoq_category
import pandas as pd

KNIME_LOGGER = logging.getLogger(__name__)

# SDF V2000 atom block line: three coordinates with a decimal point followed by the
# element symbol. The decimal point is what keeps the counts and bond blocks (integer
# only) from matching.
ATOM_POSITION_PATTERN = re.compile(
    r"\n\s+(-?\d+\.\d+)\s+(-?\d+\.\d+)\s+(-?\d+\.\d+)\s+(\w+)"
)
ATOM_LINE_PATTERN = re.compile(
    r"\n[ \t]+-?\d+\.\d+[ \t]+-?\d+\.\d+[ \t]+-?\d+\.\d+[ \t]+\w+[ \t]*"
)


def _is_missing(value) -> bool:
    return (
        value is None
        or value is pd.NA
        or (isinstance(value, float) and math.isnan(value))
    )


def _to_text(value) -> str:
    return "" if _is_missing(value) else str(value)


def _extract_atom_positions(sdf_text: str) -> list[str]:
    return [
        f"{x.rjust(10)}{y.rjust(10)}{z.rjust(10)} {atom.ljust(3)} "
        for x, y, z, atom in ATOM_POSITION_PATTERN.findall(sdf_text)
    ]


def _apply_atom_positions(original_sdf: str, positions: list[str]) -> str:
    # ATOM_LINE_PATTERN stops right after the element symbol, so the remaining fixed
    # columns of each atom line (charge, stereo, ...) are preserved.
    counter = [0]

    def _replacer(match):
        if counter[0] < len(positions):
            replacement = "\n" + positions[counter[0]]
            counter[0] += 1
            return replacement
        return match.group(0)

    return ATOM_LINE_PATTERN.sub(_replacer, original_sdf)


def _correct_structures(
    original: pd.DataFrame,
    mopac: pd.DataFrame,
    id_col: str,
    mol_col: str,
    mopac_id_col: str,
    mopac_mol_col: str,
) -> pd.DataFrame:
    """Return the MOPAC results table with its molecule column corrected.

    The "original" table is used only as a reference: its ID and molecule columns
    provide the correct bond tables, and none of its columns is carried to the output.
    For
    each result row, the original structure with the same ID supplies the bonds and
    the MOPAC structure supplies the optimized coordinates. Rows that cannot be
    corrected (no matching original, ambiguous ID, atom count mismatch) get an empty
    molecule cell and are reported in the log.
    """
    reference: dict[str, str] = {}
    ambiguous: set[str] = set()
    for _, row in original.iterrows():
        key = str(row[id_col])
        if key in reference:
            ambiguous.add(key)
            continue
        reference[key] = _to_text(row[mol_col])

    corrected: list[str | None] = []
    for _, mopac_row in mopac.iterrows():
        mol_id = str(mopac_row[mopac_id_col])
        mopac_sdf = _to_text(mopac_row[mopac_mol_col])

        if not mopac_sdf:
            # Nothing to correct; the cell stays missing.
            corrected.append(None)
            continue

        if mol_id in ambiguous:
            KNIME_LOGGER.warning(
                f'ID "{mol_id}" appears more than once in the original table; '
                "molecule cell left empty."
            )
            corrected.append(None)
            continue

        original_sdf = reference.get(mol_id, "")
        if not original_sdf:
            KNIME_LOGGER.warning(
                f'ID "{mol_id}" has no molecule in the original table; '
                "molecule cell left empty."
            )
            corrected.append(None)
            continue

        positions = _extract_atom_positions(mopac_sdf)
        original_atoms = ATOM_LINE_PATTERN.findall(original_sdf)
        if len(original_atoms) != len(positions):
            KNIME_LOGGER.warning(
                f'ID "{mol_id}": atom count differs between the MOPAC structure '
                f"({len(positions)}) and the original molecule "
                f"({len(original_atoms)}); molecule cell left empty."
            )
            corrected.append(None)
            continue

        corrected.append(_apply_atom_positions(original_sdf, positions))

    output = mopac.copy()
    output[mopac_mol_col] = corrected
    return output


@knext.node(
    name="Structure Correction",
    node_type=knext.NodeType.MANIPULATOR,
    icon_path="icons/topoq.png",
    category=topoq_category,
)
@knext.input_table(
    name="MOPAC Results",
    description="Table of MOPAC-optimized structures with an ID column, typically "
    "generated by the Batch Geometry Optimizer node. This table is used as the basis "
    "for the output.",
)
@knext.input_table(
    name="Original Molecules",
    description="Reference table with the original structures (correct bonds, "
    "stereochemistry and charges) keyed by the same IDs. Only the ID and molecule "
    "columns are used; no other column is passed to the output.",
)
@knext.output_table(
    name="Corrected Molecules",
    description="MOPAC results table with the molecule column replaced by the "
    "corrected structures, preserving the original bonds and applying the "
    "MOPAC-optimized coordinates.",
)
class MopacStructureCorrection:
    """Apply MOPAC-optimized coordinates to the original bond table.

    MOPAC `.out` files contain only XYZ coordinates. Therefore, the SDF generated by
    Open Babel from these coordinates (the "Molecule (MOPAC)" output of the Batch
    Geometry Optimizer) contains a bond table inferred from interatomic distances,
    which may be incorrect.

    This node takes the MOPAC results from the first input and the original molecules,
    including their correct bonds, stereochemistry, and charges, from the second input.

    Structures are matched by ID, and each molecule is rebuilt using the original bond
    table with the MOPAC-optimized coordinates.

    The output is the MOPAC results table with its molecule column corrected.

    The second table is used only as a reference: only the ID and molecule columns are
    read, and no other columns are included in the output.

    Structures that cannot be corrected — due to a missing matching original, an
    ambiguous ID, or a different atom count — receive an empty molecule cell. The
    reason is reported in the KNIME log.
    """

    mopac_id_column = knext.ColumnParameter(
        "ID column (MOPAC results)",
        "Column of the first input table that identifies each molecule.",
        port_index=0,
    )

    mopac_molecule_column = knext.ColumnParameter(
        "MOPAC molecule column",
        "Column of the first input table with the MOPAC-optimized structure.",
        port_index=0,
    )

    id_column = knext.ColumnParameter(
        "ID column (original)",
        "Column of the second input table that identifies each molecule.",
        port_index=1,
    )

    molecule_column = knext.ColumnParameter(
        "Molecule column (original)",
        "Column of the second input table with the original SDF structure.",
        port_index=1,
    )

    def configure(self, config_context, mopac_schema, original_schema):
        id_col = self.id_column
        mol_col = self.molecule_column
        mopac_id_col = self.mopac_id_column
        mopac_mol_col = self.mopac_molecule_column

        if not (id_col and mol_col and mopac_id_col and mopac_mol_col):
            # Columns not selected yet: the output mirrors the first input table.
            return mopac_schema

        original_cols = list(original_schema.column_names)
        mopac_cols = list(mopac_schema.column_names)

        missing = [
            col for col in (mopac_id_col, mopac_mol_col) if col not in mopac_cols
        ]
        if missing:
            raise ValueError(
                "Selected columns are missing from the first input table: "
                + ", ".join(missing)
            )
        missing = [col for col in (id_col, mol_col) if col not in original_cols]
        if missing:
            raise ValueError(
                "Selected columns are missing from the second input table: "
                + ", ".join(missing)
            )

        try:
            import knime.types.chemistry as cet

            molecule_type = knext.logical(cet.SdfValue)
        except ImportError:
            KNIME_LOGGER.warning(
                "knime.types.chemistry is not available - the molecule column will be "
                "of type String. Install the KNIME Chemistry Types extension for full "
                "SDF support."
            )
            molecule_type = knext.string()

        # Output = first input table, with the molecule column re-typed as the
        # canonical SdfValue since execute() rewrites its content.
        types = [
            molecule_type if col == mopac_mol_col else mopac_schema[col].ktype
            for col in mopac_cols
        ]
        return knext.Schema(types, mopac_cols)

    def execute(self, exec_context, mopac_table, original_table):
        id_col = self.id_column
        mol_col = self.molecule_column
        mopac_id_col = self.mopac_id_column
        mopac_mol_col = self.mopac_molecule_column

        if not (id_col and mol_col and mopac_id_col and mopac_mol_col):
            raise ValueError(
                "Select the ID and molecule columns of both input tables in the node "
                "dialog."
            )

        mopac = mopac_table.to_pandas()
        original = original_table.to_pandas()

        missing = {mopac_id_col, mopac_mol_col} - set(mopac.columns)
        if missing:
            raise ValueError(
                "The first input table must contain these columns: "
                + ", ".join(sorted(missing))
            )
        missing = {id_col, mol_col} - set(original.columns)
        if missing:
            raise ValueError(
                "The second input table must contain these columns: "
                + ", ".join(sorted(missing))
            )

        exec_context.set_progress(0.1, "Applying MOPAC coordinates...")
        output = _correct_structures(
            original, mopac, id_col, mol_col, mopac_id_col, mopac_mol_col
        )

        try:
            import knime.types.chemistry as cet

            output[mopac_mol_col] = output[mopac_mol_col].apply(
                lambda sdf: cet.SdfValue(sdf) if sdf else None
            )
        except ImportError:
            pass

        exec_context.set_progress(1.0, "Done.")
        return knext.Table.from_pandas(output)
